// User
export const LOGIN = 'LOGIN';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const LOGOUT = 'LOGOUT';
export const REGISTER = 'REGISTER';
export const RESET_LOADING = 'RESET_LOADING';
export const SET_LOADING = 'SET_LOADING';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const EDIT_PROFILE = 'EDIT_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const GET_USER_BY_USERNAME = 'GET_USER_BY_USERNAME';
export const RESET_USER_BY_USERNAME = 'RESET_USER_BY_USERNAME';
export const ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT';
export const USER_ERROR = 'USER_ERROR';

// Quotes
export const GET_ALL_QUOTES = 'GET_ALL_QUOTES';
export const GET_USER_QUOTES = 'GET_USER_QUOTES';
export const GET_QUOTE = 'GET_QUOTE';
export const ADD_QUOTE = 'ADD_QUOTE';
export const EDIT_QUOTE = 'EDIT_QUOTE';
export const DELETE_QUOTE = 'DELETE_QUOTE';
export const SET_QUOTES_LOADING = 'SET_QUOTES_LOADING';
export const RESET_QUOTES_LOADING = 'RESET_QUOTES_LOADING';
export const RESET_QUOTES_SUCCESS_MESSAGE = 'RESET_QUOTES_SUCCESS_MESSAGE';
export const SET_QUOTES_ERROR_MESSAGE = 'SET_QUOTES_ERROR_MESSAGE';
export const RESET_QUOTES_ERROR_MESSAGE = 'RESET_QUOTES_ERROR_MESSAGE';